//generated by Json to Dart Plugin
class IpModel {
  IpModel({
      this.ip, 
      this.country, 
      this.cc,});

  factory IpModel.fromJson(dynamic json) {
    return IpModel(
        ip: json['ip'],
        country: json['country'],
        cc: json['cc'],
    );
  }
  final String? ip;
  final String? country;
  final String? cc;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['ip'] = ip;
    map['country'] = country;
    map['cc'] = cc;
    return map;
  }

}