import 'package:hive/hive.dart';
import 'package:my_ip_test/core/resources/app_enums.dart';

part 'ip_model.g.dart';

//generated by Json to Dart Plugin
@HiveType(typeId: 0)
class IpModel {
  IpModel({
      this.ip, 
      this.country, 
      this.cc,});

  factory IpModel.fromJson(dynamic json) {
    return IpModel(
        ip: json['ip'],
        country: json['country'],
        cc: json['cc'],
    );
  }

  @HiveField(0)
  final String? ip;
  @HiveField(1)
  final String? country;
  @HiveField(2)
  final String? cc;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['ip'] = ip;
    map['country'] = country;
    map['cc'] = cc;
    return map;
  }

}