import 'package:hive/hive.dart';

part 'last_ip_model.g.dart';

//generated by Json to Dart Plugin
@HiveType(typeId: 1)
class LastIpModel {
  LastIpModel({this.ip, this.country, this.cc, this.dateTime});

  factory LastIpModel.fromJson(dynamic json) {
    return LastIpModel(
      ip: json['ip'],
      country: json['country'],
      cc: json['cc'],
      dateTime: json['dateTime'],
    );
  }

  @HiveField(0)
  final String? ip;
  @HiveField(1)
  final String? country;
  @HiveField(2)
  final String? cc;
  @HiveField(3)
  final DateTime? dateTime;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['ip'] = ip;
    map['country'] = country;
    map['cc'] = cc;
    map['dateTime'] = dateTime;
    return map;
  }
}